### ISSUE TITLE
MLFlow 1.26.0 has a protobuf error

### ISSUE THREAD

**Issue by tarockey** [Azure/azureml-examples#1423]
When running the example pipeline using mlflow 1.26.0 for the data prep environment, the job fails with the error:

```
Traceback (most recent call last):
  File "data_prep.py", line 6, in <module>
    import mlflow
  File "/azureml-envs/azureml_6f940507ddc8514760d8ce9d16d0026c/lib/python3.8/site-packages/mlflow/__init__.py", line 32, in <module>
    import mlflow.tracking._model_registry.fluent
  File "/azureml-envs/azureml_6f940507ddc8514760d8ce9d16d0026c/lib/python3.8/site-packages/mlflow/tracking/__init__.py", line 8, in <module>
    from mlflow.tracking.client import MlflowClient
  File "/azureml-envs/azureml_6f940507ddc8514760d8ce9d16d0026c/lib/python3.8/site-packages/mlflow/tracking/client.py", line 16, in <module>
    from mlflow.entities import Experiment, Run, RunInfo, Param, Metric, RunTag, FileInfo, ViewType
  File "/azureml-envs/azureml_6f940507ddc8514760d8ce9d16d0026c/lib/python3.8/site-packages/mlflow/entities/__init__.py", line 6, in <module>
    from mlflow.entities.experiment import Experiment
  File "/azureml-envs/azureml_6f940507ddc8514760d8ce9d16d0026c/lib/python3.8/site-packages/mlflow/entities/experiment.py", line 2, in <module>
    from mlflow.entities.experiment_tag import ExperimentTag
  File "/azureml-envs/azureml_6f940507ddc8514760d8ce9d16d0026c/lib/python3.8/site-packages/mlflow/entities/experiment_tag.py", line 2, in <module>
    from mlflow.protos.service_pb2 import ExperimentTag as ProtoExperimentTag
  File "/azureml-envs/azureml_6f940507ddc8514760d8ce9d16d0026c/lib/python3.8/site-packages/mlflow/protos/service_pb2.py", line 18, in <module>
    from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2
  File "/azureml-envs/azureml_6f940507ddc8514760d8ce9d16d0026c/lib/python3.8/site-packages/mlflow/protos/scalapb/scalapb_pb2.py", line 29, in <module>
    options = _descriptor.FieldDescriptor(
  File "/azureml-envs/azureml_6f940507ddc8514760d8ce9d16d0026c/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

Updating to 1.26.1 resolves this issue. 

https://github.com/Azure/azureml-examples/blob/a37e12877baed1d00874caa20444c3b8c5f4a026/tutorials/e2e-ds-experience/e2e-ml-workflow.ipynb?short_path=fd57f81#L362

Related Mlflow issue: https://github.com/mlflow/mlflow/issues/5949

**Comment by george-kuanli-peng** [comment]
> Updating to 1.26.1 resolves this issue.
> 
> https://github.com/Azure/azureml-examples/blob/a37e12877baed1d00874caa20444c3b8c5f4a026/tutorials/e2e-ds-experience/e2e-ml-workflow.ipynb?short_path=fd57f81#L362
> 
> Related Mlflow issue: [mlflow/mlflow#5949](https://github.com/mlflow/mlflow/issues/5949)

This workaround works for me. Thanks!
