### ISSUE TITLE
Unable to load mlflow model from /mnt/azureml/cr/j/54eb22ef76e94a02856ed4611dba04ae/cap/data-capability/wd/INPUT_model_input in current environment due to error: cannot import name 'logsumexp' from 'sklearn.utils.fixes' (/azureml-envs/responsibleai/lib/python3.8/site-packages/sklearn/utils/fixes.py)

### ISSUE THREAD

**Issue by Typod01** [Azure/azureml-examples#2594]
### Operating System

Linux

### Version Information

This issue occurs in Azure ML Studio when trying to create an RAI dashboard.

ValueError: Unable to load mlflow model from /mnt/azureml/cr/j/54eb22ef76e94a02856ed4611dba04ae/cap/data-capability/wd/INPUT_model_input in current environment due to error:
cannot import name 'logsumexp' from 'sklearn.utils.fixes' (/azureml-envs/responsibleai/lib/python3.8/site-packages/sklearn/utils/fixes.py)

It is using the prebuilt RAI environment via a pipeline job.  Not sure what other info is needed as this isn't a local issue.

### Steps to reproduce

Submit a pipeline job to create an RAI dashaboard.

### Expected behavior

I would like it to work.

### Actual behavior

it doesn't!

**Comment by Typod01** [comment]
here is the full error:

Execution failed. User process 'python' exited with status code 1. Please check log file 'user_logs/std_log.txt' for error details. Error: Traceback (most recent call last):
  File "create_rai_insights.py", line 225, in <module>
    main(args)
  File "/mnt/azureml/cr/j/fdfafc7ec99147d3b75510c41dc3f28d/exe/wd/_telemetry/_loggerfactory.py", line 143, in wrapper
    return func(*args, **kwargs)
  File "create_rai_insights.py", line 174, in main
    model_estimator = load_mlflow_model(
  File "/mnt/azureml/cr/j/fdfafc7ec99147d3b75510c41dc3f28d/exe/wd/rai_component_utilities.py", line 129, in load_mlflow_model
    raise ValueError(
ValueError: Unable to load mlflow model from /mnt/azureml/cr/j/fdfafc7ec99147d3b75510c41dc3f28d/cap/data-capability/wd/INPUT_model_input in current environment due to error:
cannot import name 'logsumexp' from 'sklearn.utils.fixes' (/azureml-envs/responsibleai/lib/python3.8/site-packages/sklearn/utils/fixes.py)
