### ISSUE TITLE
Local deployment of cli/endpoints/online/managed/simple-flow fails

### ISSUE THREAD

**Issue by ietz** [Azure/azureml-examples#646]
## Which example? Describe the issue

example: `cli/endpoints/online/managed/simple-flow/1-create-endpoint-with-blue.yml`

description:
Locally deploying this endpoint via `az ml endpoint create --local -n my-endpoint -f endpoints/online/managed/simple-flow/1-create-endpoint-with-blue.yml` fails. The command output shows "Local deployment (my-endpoint / blue) is in failed state. Try getting logs to debug scoring script.". The endpoint logs are:
```
2021-08-03T11:51:37,829194300+00:00 - rsyslog/run 
2021-08-03T11:51:37,829937200+00:00 - gunicorn/run
2021-08-03T11:51:37,830236800+00:00 - iot-server/run
2021-08-03T11:51:37,830457500+00:00 - nginx/run
EdgeHubConnectionString and IOTEDGE_IOTHUBHOSTNAME are not set. Exiting...
2021-08-03T11:51:37,927721100+00:00 - iot-server/finish 1 0
2021-08-03T11:51:37,928965000+00:00 - Exit code 1 is normal. Not restarting iot-server.
Starting gunicorn 20.1.0
Listening at: http://127.0.0.1:31311 (31)
Using worker: sync
worker timeout is set to 300
Booting worker with pid: 69
SPARK_HOME not set. Skipping PySpark Initialization.
Exception in worker process
Traceback (most recent call last):
  File "/var/azureml-server/routes_common.py", line 37, in <module>
    from azureml.api.exceptions.ClientSideException import ClientSideException
ModuleNotFoundError: No module named 'azureml.api'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda/envs/inf-conda-env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/miniconda/envs/inf-conda-env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/miniconda/envs/inf-conda-env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/miniconda/envs/inf-conda-env/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/miniconda/envs/inf-conda-env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/miniconda/envs/inf-conda-env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/miniconda/envs/inf-conda-env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/azureml-server/entry.py", line 1, in <module>
    import create_app
  File "/var/azureml-server/create_app.py", line 4, in <module>
    from routes_common import main
  File "/var/azureml-server/routes_common.py", line 39, in <module>
    from azure.ml.api.exceptions.ClientSideException import ClientSideException
ModuleNotFoundError: No module named 'azure.ml'
Worker exiting (pid: 69)
Shutting down: Master
Reason: Worker failed to boot.
2021-08-03T11:51:38,776038400+00:00 - gunicorn/finish 3 0
2021-08-03T11:51:38,777075900+00:00 - Exit code 3 is not normal. Killing image.
ERROR conda.cli.main_run:execute(34): Subprocess for 'conda run ['runsvdir', '/var/runit']' command failed.  (See above for error)
2021-08-03T11:51:38,783702300+00:00 - nginx/finish 0 0
2021-08-03T11:51:38,787859300+00:00 - Exit code 0 is not normal. Killing image.
runsvdir: no process found
```

## Additional context

- The problem is resolved when I use `mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:20210727.v1` as the docker image instead of the `:20210301.v1` tag currently used in the endpoint specification
- I got the command for local deployment from the az ml doc ["Deploy and score a machine learning model by using a managed online endpoint (preview)"](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-managed-online-endpoints) under the section "Deploy the model locally".

**Comment by hichemaichour** [comment]
[Latest docs](https://github.com/Azure/azureml-examples/blob/main/cli/endpoints/online/managed/sample/blue-deployment.yml) has already moved the image tag to the one you mentioned

**Comment by paledger** [comment]
Hi @ietz , thanks for reaching out. Sorry for such a late response, this github issue was just brought to the attention of the engineering team. 

This is a known issue when the base image is out of sync with the azureml-defaults version. Doing what you did (updating the base image to a more recent version) is our recommendation. The other option is pinning the azureml-defaults package.
